name: contactManager
version: 0.1.0
author: Jesse Riggins
dependencies:
  args: '>=0.12.0 <0.13.0'
  bootstrap_for_pub: '>=3.2.0 <4.0.0'
  start: any
  uuid: any
dev_dependencies:
  unittest: '>=0.11.0+3 <0.12.0'
